### ISSUE TITLE
0.0.10 - TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by piercers** [systemjs/plugin-babel#35] opened 2016-05-06 02:54 UTC
The update to 0.0.10 is throwing an error when I run `jspm bundle index.js -id`

This previously worked on 0.0.9:

```
Building the bundle tree for index.js...

err  TypeError: Cannot read property 'match' of null
at /Users/me/project/node_modules/systemjs-builder/lib/sourcemaps.js:62:25
at Array.forEach (native)
at SourceMapConsumer_eachMapping [as eachMapping] (/Users/me/project/node_modules/source-map/lib/source-map-consumer.js:155:14)
at /Users/me/project/node_modules/systemjs-builder/lib/sourcemaps.js:61:24
at Array.forEach (native)
at exports.concatenateSourceMaps (/Users/me/project/node_modules/systemjs-builder/lib/sourcemaps.js:42:19)
at createOutput (/Users/me/project/node_modules/systemjs-builder/lib/output.js:63:21)
at exports.writeOutputs (/Users/me/project/node_modules/systemjs-builder/lib/output.js:150:16)
at /Users/me/project/node_modules/systemjs-builder/lib/builder.js:607:14
at tryCatcher (/Users/me/project/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/Users/me/project/node_modules/bluebird/js/release/promise.js:502:31)
at Promise._settlePromise (/Users/me/project/node_modules/bluebird/js/release/promise.js:559:18)
at Promise._settlePromise0 (/Users/me/project/node_modules/bluebird/js/release/promise.js:604:10)
at Promise._settlePromises (/Users/me/project/node_modules/bluebird/js/release/promise.js:683:18)
at Promise._fulfill (/Users/me/project/node_modules/bluebird/js/release/promise.js:628:18)
at Promise._resolveCallback (/Users/me/project/node_modules/bluebird/js/release/promise.js:423:57)
```

What other info should I provide?

**Comment by guybedford** [comment] 2016-05-06 08:53
If you can share the contents of index.js that would help to replicate.

**Comment by piercers** [comment] 2016-05-06 17:56
Of course. Sorry, should have just started with a test repo.

[Here's an example with steps to reproduce](https://github.com/piercers/jspm-plugin-babel-10).

**Comment by guybedford** [comment] 2016-05-16 10:24
Thanks so much, yes this is a bug - I'm looking into it. Duplicate of https://github.com/jspm/jspm-cli/issues/1804.

**Closed by guybedford** 2016-05-16 10:24 UTC
